### ISSUE TITLE
unsubscribe of undefined calling resetTimer

### ISSUE THREAD

**Issue by Skied** [bearnithi/bn-ng-idle#2]
calling resetTimer before starting idle throws the error:

ERROR TypeError: Cannot read property 'unsubscribe' of undefined
    at BnNgIdleService.push../node_modules/bn-ng-idle/fesm5/bn-ng-idle.js.BnNgIdleService.resetTimer (bn-ng-idle.js:49)

**Comment by bearnithi** [comment]
You should start the idle, only then you can reset the timer using `resetTimer` method.
