### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Arthi93** [bearnithi/bn-ng-idle#7]
Hello,

on Angular 7 after installation i got this error:

`TypeError: Object(...) is not a function`. From googling it I assume its version incompatibility but im using 1.0.1. Any advices? Im using just the basic method:

     `this.bnIdle.startWatching(environment.sessionTimeout).subscribe((expired) => {
	    if (expired) {
		...
	    }
    });`

**Comment by Perminus-Gaita** [comment]
I have the same problem... I guess I'll just use another package.

**Comment by Arthi93** [comment]
Yeah, switched to https://github.com/moribvndvs/ng2-idle and it works without a problem

**Comment by bearnithi** [comment]
Upgrading your rxjs version to latest one. that is rxjs 6. That will solve the issue.

`npm i rxjs@^6.0 rxjs-compat`

**Comment by bearnithi** [comment]
Upgrading your rxjs version to latest one. that is rxjs 6. That will solve the issue.

`npm i rxjs@^6.0 rxjs-compat`
